### ISSUE TITLE
Cannot get rooms data

### ISSUE THREAD

**Issue by augard** [signalkraft/myPyllant#125]
### Before submitting a new issue

- [x ] I'm using the latest version of myPyllant
- [x ] I've checked [known issues](https://signalkraft.com/mypyllant-component/#known-issues)
- [ x] I'm sure this problem is about the myPyllant library. For issues with the home assistant component, [open an issue here](https://github.com/signalkraft/mypyllant-component/issues/new/choose)

### Problem description

It's log from home assistant, but from text it looks like problem in library. It's not able to get rooms data. I have Protherm version of Vaillant smart thermostat for heat pump.

```
2024-12-06 09:32:46.856 WARNING (MainThread) [myPyllant.api] Could not get rooms data
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/myPyllant/api.py", line 1400, in get_ambisense_rooms
    response = await self.aiohttp_session.get(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/myPyllant/http_client.py", line 30, in _request
    return await super()._request(method, url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client.py", line 830, in _request
    await raise_for_status(resp)
  File "/usr/local/lib/python3.13/site-packages/myPyllant/http_client.py", line 83, in on_raise_for_status
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client_reqrep.py", line 1157, in raise_for_status
    raise ClientResponseError(
    ...<5 lines>...
    )
aiohttp.client_exceptions.ClientResponseError: 409, message='Conflict', url='https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/api/v1/ambisense/facilities/b70ae729-2e29-49ca-87ec-499502c68659/rooms'
```

**Comment by CKNOEP** [comment]
SAme things for me

**Comment by Trickx** [comment]
Same for me. I tried to generate test data, but it fails with similar or the same issue.
I'm using a Vaillant FlexoTherm Exclusive (geothermal heat pump).
In my setup a single home is configured without any room, I belief
I don't use any room temperature to control heating.

```
python3 -m myPyllant.tests.generate_test_data mail@address.de Password vaillant --country germany
Generating test data for 1f6c04d060fada1cef8c607cf5d4ccea202f82ba...
Error fetching https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/api/v1/ambisense/facilities/39212441-a14a-4b04-9d2e-815e8ba8b41f/rooms: 409, message='Conflict', url='https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/api/v1/ambisense/facilities/39212441-a14a-4b04-9d2e-815e8ba8b41f/rooms'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/myPyllant/tests/generate_test_data.py", line 298, in main
    async with api.aiohttp_session.get(
               ~~~~~~~~~~~~~~~~~~~~~~~^
        rooms_url, headers=api.get_authorized_headers()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ) as rooms_resp:
    ^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/aiohttp/client.py", line 1425, in __aenter__
    self._resp: _RetType = await self._coro
                           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/myPyllant/http_client.py", line 30, in _request
    return await super()._request(method, url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/aiohttp/client.py", line 832, in _request
    await raise_for_status(resp)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/myPyllant/http_client.py", line 83, in on_raise_for_status
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/aiohttp/client_reqrep.py", line 1161, in raise_for_status
    raise ClientResponseError(
    ...<5 lines>...
    )
aiohttp.client_exceptions.ClientResponseError: 409, message='Conflict', url='https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/api/v1/ambisense/facilities/39212441-a14a-4b04-9d2e-815e8ba8b41f/rooms'
Wrote test data to /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/myPyllant/tests/data/08529458feaaaf613d67d99cebcb23f2cb1e23c0

Results are already anonymized, but the myVAILLANT API may change and contain new, sensitive data.
You should check the contents of the JSON files before sharing them.
```
No JSON file is created.

**Comment by signalkraft** [comment]
Vaillant may have changed the URL for retrieving rooms data. Because I don't have such a system, someone else would need to do some [reverse engineering](https://signalkraft.com/mypyllant-component/3-reverse-engineering/) to find out what the new endpoint is.
