### ISSUE TITLE
Home assistant HACS upgrade

### ISSUE THREAD

**Issue by ear9mrn** [signalkraft/myPyllant#15]
Not sure this is the right place to ask...

Just upgraded to a the latest version. 0.3.2 (home assistant HACS) and a couple of the entities have disappeared.

missing entities:
outside_temperature
system_water_pressure
water_pressure_ecotec
system_mode

I have a sensoCOMFORT VRC720 (wired), ecoTec Plus 624, VR66/2 control center with sensoNET and a VR10 probe (outdoor temp)

Thanks,

Pete.

**Comment by ear9mrn** [comment]
Not sure if this is related. I cloned this repo and tried to run the generate_test_data.py and get the following:

`Traceback (most recent call last):
  File "/home/pete/myPyllant/src/myPyllant/tests/generate_test_data.py", line 183, in <module>
    asyncio.run(main(args.user, args.password, args.brand, args.country))
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/pete/myPyllant/src/myPyllant/tests/generate_test_data.py", line 135, in main
    "operationMode": device["data"][0]["operation_mode"],
                     ~~~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable`

Looks like we're not getting back any info for that request although the URL seems to be good.

`https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/emf/v2/41b0569f-3c5e-4bc2-aaf8-6dc7b397a3b3/currentSystem
{'system_type': 'UNKNOWN', 'has_emf_capable_devices': False, 'primary_heat_generator': None, 'secondary_heat_generators': [], 'electric_backup_heater': None, 'solar_station': None, 'ventilation': None}
{
  "system_type": "UNKNOWN",
  "has_emf_capable_devices": false,
  "primary_heat_generator": null,
  "secondary_heat_generators": [],
  "electric_backup_heater": null,
  "solar_station": null,
  "ventilation": null
}
`
Is there another/new URL for system info?

**Comment by minosrex** [comment]
Same here. I saw the data has been unavailable for a while, but it is only with the autumn cold setting in that I started to check what the issue is with the integration. I see I get the following error as well:

Logger: homeassistant.components.binary_sensor
Source: custom_components/mypyllant_old/binary_sensor.py:32 
Integration: Binary Sensor ([documentation](https://www.home-assistant.io/integrations/binary_sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+binary_sensor%22)) 
First occurred: 15 October 2023 at 11:29:56 (1 occurrences) 
Last logged: 15 October 2023 at 11:29:56

Error while setting up mypyllant platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 362, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/mypyllant_old/binary_sensor.py", line 32, in async_setup_entry
    for index, system in enumerate(coordinator.data):
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

I reinstalled the integration, it no longer shows any entities.
