### ISSUE TITLE
Test data for flexotherm exclusive@vrc700

### ISSUE THREAD

**Issue by nicnab** [signalkraft/myPyllant#60]
[15d5d4d8373bec8a39f148f8a9fe52fed7418743.zip](https://github.com/signalkraft/myPyllant/files/14237909/15d5d4d8373bec8a39f148f8a9fe52fed7418743.zip)

Thanks for making this! It works and I get all kinds of info from the API. When calling `python3 -m myPyllant.export xxx yyy vaillant --country germany > test.json` I get this error (in addition to a filled test.json):

```
Could not get MPC data
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/myPyllant/api.py", line 1052, in get_mpc
    response = await self.aiohttp_session.get(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 691, in _request
    await raise_for_status(resp)
  File "/usr/local/lib/python3.11/dist-packages/myPyllant/api.py", line 102, in on_raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Resource Not Found', url=URL('https://api.vaillant-group.com/service-connected-control/vrc700/v1/hem/031a815a-0586-4fbf-8985-5af8428ca7ea/mpc')

```
Let me know if I can provide more info!

**Comment by signalkraft** [comment]
This should be fixed in the newer versions of the library!

**Comment by nicnab** [comment]
Confirmed - no errors anymore. Thanks! Is there a way to find out which values can be queried, like historical usage data etc?

**Comment by signalkraft** [comment]
You can add `-h` to all CLI commands and read more on https://signalkraft.com/mypyllant-component/2-library/#usage
