### ISSUE TITLE
Energy Report not working

### ISSUE THREAD

**Issue by mariolongman** [signalkraft/myPyllant#62]
Hi,

python3 -m myPyllant.report username password vaillant --country austria gives me only an error (same errer as with real user/pass):
`Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/myPyllant/report.py", line 46, in <module>
    asyncio.run(main(**kwargs))
  File "/usr/lib/python3.10/asyncio/runners.py", line 37, in run
    raise ValueError("a coroutine was expected, got {!r}".format(main))
ValueError: a coroutine was expected, got <async_generator object main at 0x7fc013982540>`

Same with the docker version: docker run -ti ghcr.io/signalkraft/mypyllant:latest python3 -m myPyllant.report username password vaillant --country austria
`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/build/src/myPyllant/report.py", line 46, in <module>
    asyncio.run(main(**kwargs))
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 89, in run
    raise ValueError("a coroutine was expected, got {!r}".format(coro))
ValueError: a coroutine was expected, got <async_generator object main at 0x7fdd1ead6260>`

is there a problem with the energy report at the moment?

regards

**Comment by mariolongman** [comment]
Thank you, with latest version problem is gone 👍
