### ISSUE TITLE
Missing value for field "is_cooling_allowed"

### ISSUE THREAD

**Issue by j-otten** [signalkraft/myPyllant#72]
### Before submitting a new issue

- [x] I'm using the latest version of myPyllant
- [x] I've checked [known issues](https://signalkraft.com/mypyllant-component/#known-issues)
- [x] I'm sure this problem is about the myPyllant library. For issues with the home assistant component, [open an issue here](https://github.com/signalkraft/mypyllant-component/issues/new/choose)

### Problem description
Hi,

i've written a short script for my smart home that pulls data from myVaillant to save them to Influx using the myPyllant libary.
Before the 1st of march everything works fine but now the libary throws the following error:

_dacite.exceptions.MissingValueError: missing value for field "is_cooling_allowed"_

Seems like the expected value is not longer included in the vaillant api.

The relevant part of my code looks like this:
```
async with MyPyllantAPI(user, password, brand, country) as api:
     async for system in api.get_systems():`
```

**Stack Trace:**
```
`During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\USERNAME\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\myPyllant\export.py", line 94, in <module>
    asyncio.run(main(**kwargs))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\myPyllant\export.py", line 59, in main
    async for system in api.get_systems(
  File "C:\Users\USERNAME\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\myPyllant\api.py", line 321, in get_systems
    system = System.from_api(
             ^^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\myPyllant\models.py", line 324, in from_api
    system.circuits = [
                      ^
  File "C:\Users\USERNAME\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\myPyllant\models.py", line 325, in <listcomp>
    Circuit.from_api(system_id=system.id, **c)
  File "C:\Users\USERNAME\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\myPyllant\models.py", line 122, in from_api
    return from_dict(
           ^^^^^^^^^^
  File "C:\Users\USERNAME\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\dacite\core.py", line 76, in from_dict
    raise MissingValueError(field.name)
dacite.exceptions.MissingValueError: missing value for field "is_cooling_allowed"`

```

**Comment by j-otten** [comment]
Deleting an reinstalling the libary did the trick - closing here..

**Comment by j-otten** [comment]
Deleting an reinstalling the libary did the trick - closing here..
