### ISSUE TITLE
No Entities - Arotherm Plus, UniTower, Sensonet, VR921

### ISSUE THREAD

**Issue by CommanderROR9** [signalkraft/myPyllant#9]
Sadly myVaillant integration gives me 0 entities...

2023-06-06 19:57:20.205 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session
2023-06-06 19:57:20.233 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connector
2023-06-06 19:57:21.891 ERROR (MainThread) [custom_components.mypyllant] Unexpected error fetching myVAILLANT data: 'index'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/mypyllant/__init__.py", line 140, in _async_update_data
    data = [
  File "/config/custom_components/mypyllant/__init__.py", line 140, in <listcomp>
    data = [
  File "/usr/local/lib/python3.10/site-packages/myPyllant/api.py", line 256, in get_systems
    system = System(
  File "/usr/local/lib/python3.10/site-packages/myPyllant/models.py", line 158, in __init__
    self.zones = [Zone(system_id=self.id, **z) for z in self._merged_zones]
  File "/usr/local/lib/python3.10/site-packages/myPyllant/models.py", line 158, in <listcomp>
    self.zones = [Zone(system_id=self.id, **z) for z in self._merged_zones]
  File "/usr/local/lib/python3.10/site-packages/myPyllant/models.py", line 187, in _merge_object
    state = [c for c in self.state.get(obj_name, []) if c["index"] == idx][0]
  File "/usr/local/lib/python3.10/site-packages/myPyllant/models.py", line 187, in <listcomp>
    state = [c for c in self.state.get(obj_name, []) if c["index"] == idx][0]
KeyError: 'index'
2023-06-06 19:57:22.157 ERROR (MainThread) [custom_components.mypyllant] Unexpected error fetching myVAILLANT data: 'index'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/mypyllant/__init__.py", line 157, in _async_update_data
    async for system in await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/site-packages/myPyllant/api.py", line 256, in get_systems
    system = System(
  File "/usr/local/lib/python3.10/site-packages/myPyllant/models.py", line 158, in __init__
    self.zones = [Zone(system_id=self.id, **z) for z in self._merged_zones]
  File "/usr/local/lib/python3.10/site-packages/myPyllant/models.py", line 158, in <listcomp>
    self.zones = [Zone(system_id=self.id, **z) for z in self._merged_zones]
  File "/usr/local/lib/python3.10/site-packages/myPyllant/models.py", line 187, in _merge_object
    state = [c for c in self.state.get(obj_name, []) if c["index"] == idx][0]
  File "/usr/local/lib/python3.10/site-packages/myPyllant/models.py", line 187, in <listcomp>
    state = [c for c in self.state.get(obj_name, []) if c["index"] == idx][0]
KeyError: 'index'
2023-06-06 19:57:22.419 ERROR (MainThread) [custom_components.mypyllant] Unexpected error fetching myVAILLANT data: 'index'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/mypyllant/__init__.py", line 178, in _async_update_data
    async for system in await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/site-packages/myPyllant/api.py", line 256, in get_systems
    system = System(
  File "/usr/local/lib/python3.10/site-packages/myPyllant/models.py", line 158, in __init__
    self.zones = [Zone(system_id=self.id, **z) for z in self._merged_zones]
  File "/usr/local/lib/python3.10/site-packages/myPyllant/models.py", line 158, in <listcomp>
    self.zones = [Zone(system_id=self.id, **z) for z in self._merged_zones]
  File "/usr/local/lib/python3.10/site-packages/myPyllant/models.py", line 187, in _merge_object
    state = [c for c in self.state.get(obj_name, []) if c["index"] == idx][0]
  File "/usr/local/lib/python3.10/site-packages/myPyllant/models.py", line 187, in <listcomp>
    state = [c for c in self.state.get(obj_name, []) if c["index"] == idx][0]
KeyError: 'index'
2023-06-06 19:57:22.427 WARNING (MainThread) [custom_components.mypyllant.binary_sensor] No system data, skipping binary sensors
2023-06-06 19:57:22.429 WARNING (MainThread) [custom_components.mypyllant.sensor] No system data, skipping sensors
2023-06-06 19:57:22.431 WARNING (MainThread) [custom_components.mypyllant.sensor] No hourly data, skipping sensors
2023-06-06 19:57:22.432 WARNING (MainThread) [custom_components.mypyllant.sensor] No daily data, skipping sensors
2023-06-06 19:57:22.434 WARNING (MainThread) [custom_components.mypyllant.climate] No system data, skipping climate
2023-06-06 19:57:22.436 WARNING (MainThread) [custom_components.mypyllant.water_heater] No system data, skipping water hearer

**Comment by CommanderROR9** [comment]
Update: downgrading to Version 0.2 helped. It seems to be working fine now.

**Comment by RainerPopella** [comment]
Hi,
Please have a look  at issue "Problem with COPY and REFERENCE in models.py". I assume that is the reason for your problem.
KR Rainer
